### PR TITLE
Fixing Incorrect Keyboard Style

### LINKED ISSUE #599: Editor: Incorrect Keyboard Style
### Details:
Simplenote's Editor keyboard style isn't properly respecting the preferences.

0. Toggle your device's Theme to Dark
1. Launch Simplenote
2. Toggle Simplenote settings to Light Mode
3. Open the Editor
4. Press anywhere to trigger the First Responder

As a result, the keyboard will be rendered in dark.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're fixing a bug that's causing the Editor's Keyboard Style to show up with the incorrect appearance type.

Closes #599

### Test
1. Toggle your device's Theme to Dark
2. Launch Simplenote
3. Toggle Simplenote settings to Light Mode
4. Relaunch the app (just in case!)
5. Open the Editor
6. Press anywhere to trigger the First Responder

- [x] Verify the keyboard shows up in Light Mode!

### Release
`RELEASE-NOTES.txt` was updated in 8900c2e with:

> Fixed a bug that caused the Editor's Keyboard Appearance not to match the selected theme

### CODE REVIEW

File: Simplenote/Classes/SPNoteEditorViewController.m [hunk 1]
```diff
@@ -131,6 +121,22 @@ - (instancetype)init {
     return self;
 }
 
+- (void)configureTextView
```
Comment (bummytime) [inline Simplenote/Classes/SPNoteEditorViewController.m]: Thank you for pulling this out of `init()` 🙇

File: Simplenote/Classes/SPNoteEditorViewController.m [hunk 2]
```diff
@@ -339,6 +344,27 @@ - (void)willTransitionToTraitCollection:(UITraitCollection *)newCollection withT
...
+- (void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection
+{
+    [super traitCollectionDidChange:previousTraitCollection];
+
+    if (@available(iOS 13.0, *)) {
+        if (self.traitCollection.userInterfaceStyle == previousTraitCollection.userInterfaceStyle) {
+            return;
+        }
+
+        // Okay. Let's talk.
```
Comment (bummytime) [inline Simplenote/Classes/SPNoteEditorViewController.m]: 😆

File: Simplenote/Classes/SPNoteEditorViewController.m [hunk 3]
```diff
@@ -339,6 +344,27 @@ - (void)willTransitionToTraitCollection:(UITraitCollection *)newCollection withT
...
+        // Whenever `applyStyle` gets called whenever this VC is not really onScreen, it might have issues with SPUserInteface.isDark
+        // (since the active traits might not really match the UIWindow's traits).
+        //
+        // For the above reason, we _must_ listen to Trait Change events, and refresh the style appropriately.
+        //
+        // Ref. https://github.com/Automattic/simplenote-ios/issues/599
+        //
+        [self applyStyle];
```
Comment (bummytime) [inline Simplenote/Classes/SPNoteEditorViewController.m]: 👍

**Comment by jleandroperez** [comment]
And off we go!! 🔥 

Thank you Bummy!!
