### PR TITLE
Fixed tag bar getting stuck on swipe to markdown preview

### LINKED ISSUE #1211: TagsEditor Stuck When swiping to markdown preview
### Details
While testing #1200 I've spotted a VoiceOver bug:

1. Open the Editor
2. Enable VoiceOver
3. Push the Markdown Preview via the 3 finger right swipe
4. Go back to the editor

As a result, the Keyboard will be dismissed, but the Tags Editor will remain visible in the middle of the screen.

### Demo
https://user-images.githubusercontent.com/1195260/111329169-b0198b80-864d-11eb-920b-67bbd634c131.mp4

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
Fixes #1211 
This PR fixes a problem with the tag bar where swiping from the note editor to markdown preview, while the keyboard was visible, would cause the tag bar to get stuck in the middle of the screen. 

The tag list location is animated in and out based on the changes to the keyboard, so with this PR, I have changed when the Note Editor stops listening to keyboard update notifications.  The keyboard was being dismissed after we stopped listening, so the tags bar had no way to know it needed to change locations.

### Test
1. go to a note that has mark down enabled.  
2. tap into the text view to make the keyboard appear
3. swipe to the left to make markdown appear
4. tap back to return to the editor
The tag bar should be at the bottom of the screen not in the middle

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer  is required to review these changes, but anyone can perform the review.

### CODE REVIEW

File: Simplenote/Classes/SPNoteEditorViewController.m [hunk 1]
```diff
@@ -211,11 +211,15 @@ - (void)viewWillDisappear:(BOOL)animated
...
     [super viewWillDisappear:animated];
     [self.navigationController setToolbarHidden:YES animated:YES];
-    [self stopListeningToKeyboardNotifications];
 
     [self saveScrollPosition];
 }
 
+- (void)viewDidDisappear:(BOOL)animated
+{
+    [self stopListeningToKeyboardNotifications];
```
Comment (jleandroperez) [inline Simplenote/Classes/SPNoteEditorViewController.m:221]: Nipticky: `[super viewDidDisappear:animated]` on this one

**Review by jleandroperez — APPROVED** [review]
Works super! one nipticky comment, feel free to merge afterwards!

Thanks for fixing this sir!!

:shipit:
