### PR TITLE
Notes List: Fixing Checklist Processing

### LINKED ISSUE #663: Checklists not properly processed in Notes List
### Details:
1. Add a new note with the following text
   ```
   - [ ] Uno
   - [ ] Dos
   - [ ] Tres
   - [ ] Catorce
   ```
2. Open the Notes List

As a result you'll get the following. Note that `Tres` and `Catorce` don't really get their bullets in place!

H/t @theck13  (Thank you!!)

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're:

1. Fixing Checklists Processing in the Notes List, so that not just the first Checkbox will get replaced by an image.
2. Adding new Unit Tests
3. And doing an overall cleanup

cc @bummytime (Thanks in advance Bummy!!)
Closes #663

### Test
1. Add a new note with the following content:
  ```
  - [ ] Uno
  - [ ] Dos
  - [ ] Tres
  - [ ] Catorce
  ```
2. Go back to the Notes List

- [ ] Verify every single checkmark gets a proper Checklist Image
- [x] Verify that the Checkmark aligns perfectly when the Dynamic Type settings are changed
- [x] Verify that the new Unit Tests are green

### Release
These changes do not require release notes.

### CODE REVIEW

File: Simplenote/Classes/NSRegularExpression+Simplenote.swift [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+// MARK: - NSRegularExpression
+//
+extension NSRegularExpression {
+
+    /// Matches Checklists at the beginning of each line
+    ///
+    @objc
+    static let regexForChecklists: NSRegularExpression = {
+        try! NSRegularExpression(pattern: "^\\s*(-[ \t]+\\[[xX\\s]\\])", options: .anchorsMatchLines)
```
Comment (dmsnell) [inline Simplenote/Classes/NSRegularExpression+Simplenote.swift]: In the Electron app we use this…

`^(\s*)(-[ \t]+\[[xX\s]?\])(.+)`

Looks like the difference is that in the Electron app we treat ` - [] ` as an unchecked todo. I'm not sure this is right from a purity standpoint though it probably is easier for people who don't expect that they need the space inside the box.

Just pointing out the difference is all

Comment (jleandroperez) [reply Simplenote/Classes/NSRegularExpression+Simplenote.swift]: Thanks for mentioning this @dmsnell, I'll get the regex updated so that the behavior is the same!

**Comment by jleandroperez** [comment]
cc @aerych sir, if you do get a chance, mind taking a peek at this one?

**Thanks in advance!!!**

**Comment by aerych** [comment]
Hola @jleandroperez 👋 

Noticing some weirdness while testing. 

First up, when the cursor precedes the checkbox, hitting enter will create a new checkbox on the same line.  Also, when enter is pressed any empty lines preceding the checkbox will be deleted.  Here's a demo:
checkmark-oddities

Next, if I tap back, I can see the checkboxes as part of the same line in the row. If I view the detail again, some of the extra checkboxes are not shown as an image. 
Screen Shot 2020-02-27 at 2 50 42 PM
Screen Shot 2020-02-27 at 2 50 51 PM

Finally, and this might be unrelated, but if I try to swipe to delete the row with the checkboxes, a different row is animated. (If you look closely, you'll see the correct cell is highlighted before the swipe action starts.)  Example:
swipe-wrong-cell

Thoughts on these?

File: Simplenote/Classes/NSString+Simplenote.swift [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+
+// MARK: - NSString Simplenote Helpers
+//
+extension NSString {
+
+    /// Returns the full range of the receiver
+    ///
+    @objc
+    var rangeOfEntireString: NSRange {
```
Comment (aerych) [inline Simplenote/Classes/NSString+Simplenote.swift]: `fullRange` to be a slightly more concise? `self.fullRange` vs `self.rangeOfEntireString`. Thoughts?

**Comment by aerych** [comment]
Another oddity... 
Follow the test steps to create a list.
Long press on any of the checklist items. Keep long pressing. Crash 💥 
> 2020-02-27 15:34:36.181410-0600 Simplenote[40915:607464] *** Assertion failure in -[SPEditorTextView startInteractionWithLinkAtPoint:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.54.4/UITextView_LinkInteraction.m:420
2020-02-27 15:34:36.184093-0600 Simplenote[40915:607464] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112b3b1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000112f93031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112b40472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010e963652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000011052ffec -[UITextView(LinkInteraction) startInteractionWithLinkAtPoint:] + 319
	5   UIKit                               0x000000010fd45679 -[UITextGestureClusterLinkInteract smallDelayRecognizer:] + 607
	6   UIKit                               0x000000010fd6154f -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	7   UIKit                               0x000000010fd6a324 _UIGestureRecognizerSendTargetActions + 109
	8   UIKit                               0x000000010fd67b6c _UIGestureRecognizerSendActions + 307
	9   UIKit                               0x000000010fd66dc0 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 859
	10  UIKit                               0x000000010fd4be24 _UIGestureEnvironmentUpdate + 1329
	11  CoreFoundation                      0x0000000112add607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	12  CoreFoundation                      0x0000000112add55e __CFRunLoopDoObservers + 430
	13  CoreFoundation                      0x0000000112ac1b81 __CFRunLoopRun + 1537
	14  CoreFoundation                      0x0000000112ac130b CFRunLoopRunSpecific + 635
	15  GraphicsServices                    0x00000001174c8a73 GSEventRunModal + 62
	16  UIKit                               0x000000010f769057 UIApplicationMain + 159
	17  Simplenote                          0x000000010c5d3ef0 main + 112
	18  libdyld.dylib                       0x00000001149ef955 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by aerych** [comment]
And another one... 
Create a new note. Past some text.  Ctrl+Z to undo. No problem. Now repeat, but this time paste the example checklist, then try to undo.  💥 
> 2020-02-27 15:37:20.654677-0600 Simplenote[40942:609394] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {0, 44} out of bounds; string length 28'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010829b1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001086f3031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108310975 +[NSException raise:format:] + 197
	3   CoreFoundation                      0x00000001081fd113 -[__NSCFString substringWithRange:] + 163
	4   UIKit                               0x0000000105d17c5e -[NSTextStorage(UIKitUndoExtensions) _undoRedoAttributedSubstringFromRange:] + 136
	5   UIKit                               0x0000000105d180bd -[_UITextUndoOperationReplace undoRedo] + 319
	6   Foundation                          0x00000001040bb695 -[_NSUndoStack popAndInvoke] + 280
	7   Foundation                          0x00000001040bb424 -[NSUndoManager undoNestedGroup] + 433
	8   UIKit                               0x0000000128f72863 -[NSUndoManagerAccessibility undo] + 64
	9   UIKit                               0x00000001051c9e87 -[UIKeyboardImpl handleKeyCommand:repeatOkay:beforePublicKeyCommands:] + 5297
	10  UIKit                               0x0000000104ee50c8 -[UIApplication _handleKeyUIEvent:] + 694
	11  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	12  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	13  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	14  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	15  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	16  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	17  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	18  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	19  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	20  UIKit                               0x00000001050f8cdb -[UIResponder _handleKeyUIEvent:] + 79
	21  UIKit                               0x0000000104ee4b3c -[UIApplication handleKeyUIEvent:] + 103
	22  UIKit                               0x0000000104ee4ab5 -[UIApplication handleKeyHIDEvent:] + 692
	23  UIKit                               0x0000000128ef3c80 -[UIApplicationAccessibility handleKeyHIDEvent:] + 41
	24  UIKit                               0x0000000105824fa8 __dispatchPreprocessedEventFromEventQueue + 997
	25  UIKit                               0x00000001058282c4 __handleEventQueueInternal + 5949
	26  CoreFoundation                      0x000000010823dbb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	27  CoreFoundation                      0x00000001082224af __CFRunLoopDoSources0 + 271
	28  CoreFoundation                      0x0000000108221a6f __CFRunLoopRun + 1263
	29  CoreFoundation                      0x000000010822130b CFRunLoopRunSpecific + 635
	30  GraphicsServices                    0x000000010cc28a73 GSEventRunModal + 62
	31  UIKit                               0x0000000104ec9057 UIApplicationMain + 159
	32  Simplenote                          0x0000000101d33ef0 main + 112
	33  libdyld.dylib                       0x000000010a14f955 start + 1
	34  ???                                 0x0000000000000001 0x0 + 1
)

File: Simplenote/Classes/NSString+Simplenote.swift (hunk 2 above)
Comment (jleandroperez) [reply Simplenote/Classes/NSString+Simplenote.swift]: Sold!! Updating, thank you Eric!!

**Comment by jleandroperez** [comment]
Thanks for the **SUPER AWESOME** review Eric!!!!!

I've added new issues for the following (including the crashers, wanna triple check those!):

1. Incorrectly prepended markers > #680
2. Long Press Crash > #681 
3. Undo Crash > #682

As per the inconsistency you've spotted, I'm afraid is a known issue:

> Next, if I tap back, I can see the checkboxes as part of the same line in the row. If I view the detail again, some of the extra checkboxes are not shown as an image.

Apologies I didn't mention anything about it, was extensively discussed over Slack, and I was sure it was documented.

The long short story is: multiple checklists in the same line are actually invalid, and do get rendered in the Notes List because it's the shortest / simplest way to fix Issue #663. 
Both iOS and Android behave the same way, we'll probably revisit when Checklists get some love, I'd like to do something in the Aztec lines there!!

File: Simplenote/NSMutableAttributedString+Styling.m [hunk 3]
```diff
@@ -1,62 +1,66 @@
...
-    NSArray *matches = [regex matchesInString:noteString options:0 range:[noteString rangeOfString:noteString]];
-    
-    if (matches.count == 0) {
-        return;
-    }
-    
-    int positionAdjustment = 0;
-    CGFloat fontSize = [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline].pointSize + 4;
+
+    NSString *plainString = self.string.copy;
```
Comment (aerych) [inline Simplenote/NSMutableAttributedString+Styling.m]: If I'm being nitpicky, I'd say since `copy` is a method and not a property it should be refereneced as `[self.string copy]` rather than use dot notation.  I'm not sure I'm being that picky tho ;)

Comment (aerych) [reply Simplenote/NSMutableAttributedString+Styling.m]: Swift syntax seeping into objc code style. :)  I'm noticing lots of methods called via dot notation in other places too.

File: Simplenote/NSMutableAttributedString+Styling.m [hunk 4]
```diff
@@ -1,62 +1,66 @@
...
+    NSRegularExpression *regex = allowsMultiplePerLine ? NSRegularExpression.regexForChecklistsEmbeddedAnywhere : NSRegularExpression.regexForChecklists;
+    NSArray *matches = [regex matchesInString:plainString options:0 range:plainString.fullRange];
```
Comment (aerych) [inline Simplenote/NSMutableAttributedString+Styling.m]: Ya know... if you were to do something like:
`[[[regex matchesInString:plainString options:0 range:[plainString fullRange]] reverseObjectEnumerator] allObjects]`
you could probably get rid of `positionAdjustment` and all the fussing with `adjustedRange`.

**Comment by jleandroperez** [comment]
@aerych And I keep forgetting about that trick!! (reverse enumerator >> zero issues). Mind taking a quiiiick peek, just in case?

Thank you sir!!!

File: Simplenote/NSMutableAttributedString+Styling.m [hunk 5]
```diff
@@ -16,17 +16,13 @@ - (void)processChecklistsWithColor:(UIColor *)color
...
 
     for (NSTextCheckingResult *match in matches) {
         NSRange matchedRange = match.range;
-        if (matchedRange.location == NSNotFound) {
-            continue;
-        }
-
-        NSRange adjustedRange = NSMakeRange(matchedRange.location - positionAdjustment, matchedRange.length);
-        if (NSMaxRange(adjustedRange) > self.length) {
+        if (matchedRange.location == NSNotFound || NSMaxRange(matchedRange) > self.length) {
```
Comment (aerych) [inline Simplenote/NSMutableAttributedString+Styling.m]: Not sure if this is necessary since we're not using capture groups and the matched range should never be greater than self.length.  Works for a safety net if we're paranoid. :)

Comment (jleandroperez) [reply Simplenote/NSMutableAttributedString+Styling.m]: Yyyyyeah let's keep it if you don't mind!! _just in case_, should not happen... buuut shouldn't hurt either!!

**Comment by jleandroperez** [comment]
Thank you Eric!!!
