### PR TITLE
Issue/1407 reference count incorrect

### LINKED ISSUE #1147: [Info Sheet] References count is not counting right
### Expected
References count should show the count of usage in every note separately

### Observed
When the note is referenced in other notes, the ref. count will show the same number for each note where it's referenced (i.e. total number of references VS individual number of references):

Screenshot_2021-02-12 11 44 50_ooWsfL

### Reproduced
1. Copy an internal like of Note1
2. Insert the link into Note2 once and Note3 also once
3. Open Note1
4. Open Info Sheet and check the references number ~> 

**Actual**: it shows '2' for Note2 and '2' for Note3.
**Expected**: should show '1' for both

**Additionally**: it also looks like references inside note are not counted correctly. For example, referencing Note1 in Note2 twice will still show 1 reference.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.3|4.32.0.0
iPad|Pro (Sim)|14.4|4.32.0.0

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
This PR updates the reference count logic in the Note Information sheet to calculate the number of internal references are contained in a linked note.  This fixes #1147 

Previous:

New:
 

### Test
***(Required)*** List the steps to test the behavior.  For example:
1. Create a note to be the note that is referenced to (NoteA).
2. In the new note, go to the note menu > Get internal link
3. go to another note (NoteB) and paste in the internal link one time into the note
4. Go to a third note (NoteC) and paste the internal link two different times in the content of the note
5. Return to NoteA and open the information sheet

There you should see both NoteB and NoteC listed as references, noteB should say 1 reference noteC should say 2

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer is required to review these changes, but anyone can perform the review.

### CODE REVIEW

File: Simplenote/Classes/String+Simplenote.swift [hunk 1]
```diff
@@ -171,3 +171,10 @@ extension String {
         return ContentSlice(content: self, range: lowerBound..<upperBound, matches: matchingWordsRange)
     }
 }
+
+// MARK: Substring Instance Count
+extension String {
+    func occurancesOf(_ string: String) -> Int {
```
Comment (eshurakov) [inline Simplenote/Classes/String+Simplenote.swift]: Should it be `occurrences`? 🤔 

Interesting approach, too bad swift doesn't have a built in method for that 😞

File: Simplenote/Note+Links.swift [hunk 2]
```diff
@@ -36,4 +36,9 @@ extension Note {
 
         return SimplenoteConstants.simplenotePublishedBaseURL + targetURL
     }
+
+    static func instancesOfReferenceToNoteWith(simperiumKey: String, in content: String) -> Int {
+        let internalLink = SimplenoteConstants.simplenoteScheme + "://" + SimplenoteConstants.simplenoteInterlinkHost + "/" + simperiumKey
+        return content.occurancesOf(internalLink)
+    }
```
Comment (eshurakov) [inline Simplenote/Note+Links.swift]: How about `func instancesOfReference(to note: Note) -> Int`? Seems cleaner and we can put all the logic here.
We can also reuse `plainInternalLink` here, which will remove code duplication.

File: SimplenoteTests/StringSimplenoteTests.swift [hunk 3]
```diff
@@ -104,4 +104,20 @@ extension StringSimplenoteTests {
...
     }
 
+    /// Verifies the correct return from occurancesOf
+    ///
+    func testOccurancesOfReturnsCorrectValue() {
+        let sampleA = "test x value, x test"
+        let sampleB = "test x value x"
+        let sampleC = "x test x value"
+        let sampleD = "X test X value"
+        let sampleE = "x test xxx valxue"
```
Comment (eshurakov) [inline SimplenoteTests/StringSimplenoteTests.swift:114]: It's good to test and empty case here as well.

File: SimplenoteTests/InterlinkResultsControllerTests.swift [hunk 4]
```diff
@@ -105,6 +105,20 @@ class InterlinkResultsControllerTests: XCTestCase {
...
+        let noteContentWithOneReference = "This note refers to \(plainInternalLink) one time"
+        let noteContentWithTwoReferences = "This note refers to \(plainInternalLink) two times: \(plainInternalLink)"
+        let noteContentWithOutRefernces = "No references"
+        let contentWithKeyNotLink = "this note hase the \(simperiumKey) but not a link"
+
+        XCTAssertEqual(Note.instancesOfReferenceToNoteWith(simperiumKey: simperiumKey, in: noteContentWithOneReference), 1)
+        XCTAssertEqual(Note.instancesOfReferenceToNoteWith(simperiumKey: simperiumKey, in: noteContentWithTwoReferences), 2)
+        XCTAssertEqual(Note.instancesOfReferenceToNoteWith(simperiumKey: simperiumKey, in: noteContentWithOutRefernces), 0)
+        XCTAssertEqual(Note.instancesOfReferenceToNoteWith(simperiumKey: simperiumKey, in: contentWithKeyNotLink), 0)
+    }
```
Comment (eshurakov) [inline SimplenoteTests/InterlinkResultsControllerTests.swift]: I think it's better to put it in a separate test class, because it doesn't test InterlinkResultsController, but Note extension.

**Review by eshurakov — COMMENTED** [review]
Hey Charlie, sending you a few comments!

File: Simplenote/Information/NoteInformationController.swift [hunk 5]
```diff
@@ -141,12 +141,14 @@ private extension NoteInformationController {
...
 
-        let referenceRows = references.map { (note) -> Row in
-            let date = DateFormatter.dateFormatter.string(from: note.modificationDate)
-            let value = "\(Localization.interlinkReferences(references.count)), \(Localization.lastModified(date))"
-
-            return .reference(interLink: note.plainInternalLink,
-                              title: note.titlePreview,
+        let referenceRows = references.map { (referenceNote) -> Row in
+            let date = DateFormatter.dateFormatter.string(from: referenceNote.modificationDate)
+            let value = Localization.interlinkReferences(Note.instancesOfReferenceToNoteWith(simperiumKey: note.simperiumKey, in: referenceNote.content)) +
```
Comment (jleandroperez) [inline Simplenote/Information/NoteInformationController.swift]: For readability purposes, can we move the `Note.instancesOfReferenceToNoteWith()` invocation up, and assign that to a constant?

Comment (charliescheer) [reply Simplenote/Information/NoteInformationController.swift]: Yes we can.

File: Simplenote/Classes/String+Simplenote.swift (hunk 1 above)
Comment (charliescheer) [reply Simplenote/Classes/String+Simplenote.swift]: yes it should...  Spelling is not my greatest skill... fixed

File: Simplenote/Note+Links.swift (hunk 2 above)
Comment (charliescheer) [reply Simplenote/Note+Links.swift]: Thanks for the suggestions on how I can make that work with the unit tests.  Was able to get that working with `func instancesOfReference(to note: Note) -> Int`

**Comment by charliescheer** [comment]
Thanks for the suggestions @eshurakov  and @jleandroperez  I have updated the PR.  When you have a moment, can y'all take another look.  I think it is good to go

File: SimplenoteTests/NoteExtensionTests.swift [hunk 6]
```diff
@@ -0,0 +1,48 @@
+import XCTest
+@testable import Simplenote
+
+
+// MARK: - Note+Extension Tests
+//
+class NoteExtensionTests: XCTestCase {
```
Comment (jleandroperez) [inline SimplenoteTests/NoteExtensionTests.swift]: Maybe `NoteLinkTests` ? (since there's another Extension per se)

File: Simplenote/Note+Links.swift [hunk 7]
```diff
@@ -36,4 +36,11 @@ extension Note {
 
         return SimplenoteConstants.simplenotePublishedBaseURL + targetURL
     }
+
+    func instancesOfReference(to note: Note) -> Int {
+        guard let internalLink = note.plainInternalLink else {
+            return 0
```
Comment (jleandroperez) [inline Simplenote/Note+Links.swift]: `return .zero` looks sooo much cooler 😂

**Review by jleandroperez — APPROVED** [review]
Thank you for fixing this @charliescheer !!

:shipit:

**Comment by pachlava** [comment]
[testing] fix/feature verified on iPhone XR | iOS 14.4 | Simplenote 4.33.0.0
