### PR TITLE
Nukes Appbot

### LINKED ISSUE #439: Replace AppbotX Dependency
### Details:
We've retired the AppbotX dependency several years ago. Let's implement, instead, the new mechanism that allows users to rate our app, without leaving the main interface.

### LINKED ISSUE #450: Send Feedback prompt after new install always shows error
### Expected

Send Feedback prompt displayed to new users who choose "Could be better" should allow the user to send feedback.

### Observed

Clicking send on the feedback prompt for new users seems to always produce the Error:
"There was an error sending your feedback, please try again." 

### Reproduced

 1. Complete a fresh install of Simplenote so that the "What do you think about Simplenote?" prompt is shown. (May take a few minutes and a few times of exiting and entering the app to get the prompt.)
 2. Click "Could be better" then => "Send Feedback."
 3. Fill in your email and a message, click send

*Note - I verified wifi was working, and that I was using an email account used on the device, and that the email account matched the Simplenote account in case that mattered, but it still did not work. 

iPad Pro|12.9 inch| iOS 12.4 |Simplenote 4.10.1

IMG_0012

### LINKED ISSUE #474: Dark Mode - Feedback email field has "invisible" text
### Expected
When the dialog asking me for feedback pops up, I type my email address into the text field provided, and I should see the text I'm typing.

### Observed
I can't see the text. The text field text colour is no doubt set to "Default Label" so it's going white for Dark Mode, but the text field background is white -> invisible text.

I didn't take a screenshot - sorry! Also now I can't find out how to manually launch the feedback dialog (perhaps it's not possible? I searched in Settings..)

iPhone 8 - iOS 13.1.2

### LINKED ISSUE #488: Review Prompt: Update Strings
### Details:
Let's update the Rating Prompt string as follows:

```
Great! Mind leaving a review to tell us what you like?
```

**Plus:** In general, the preference would be for all the button text to be sentence case — that is, not all capital letters. So “I like it,” “Could be better,” “Send feedback,” “No thanks,” and “Leave a review.

Thank you @michelleweber ❤️

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're nuking an external depedency (Appbot), and instead, wiring iOS's StoreKit Review API(s).

(Yes, we're closing 4 issues in a single shot. Wooow!)

@bummytime Mind taking a look sir?. I **always** wanted to drop AppBot!!! 

Closes #439
Closes #488
Closes #474
Closes #450

### Scenario: AppStore Review
0. Check out commit 13b733e in order to force the RatingsUI to always show up
1. Log into your account
2. Press **I like it** over the RatingsUI (TableView's Header) 
3. Verify the Header reads as **Great! Mind leaving a review to tell us what you like?**
4. Press **Leave a review**

- [x] Verify the app prompts for review using the SDK's Alert

### Scenario: Feedback
0. Check out commit 13b733e in order to force the RatingsUI to always show up
1. Launch simplenote on a device with Mail set-up
2. Log into your account
3. Press **Could be better** over the RatingsUI (TableView's Header)
4. Verify the Header reads as **Could you tell us how we could improve?**
5. Press **Send Feedback**

- [x] Verify Apple Mail is launched
- [x] Verify that this exact same flow, in the simulator, falls back to Safari ([and opens this](https://simplenote.com/contact-us/))

### Scenario: Dynamic Type
0. Check out commit 13b733e in order to force the RatingsUI to always show up
1. Log into your account

- [x] Verify the Ratings Header shows up, and reads as **What do you think about Simplenote?**
- [x] Verify the new Ratings UI reacts great when Dynamic Type is enabled

### Release
These changes do not require release notes.

### CODE REVIEW

File: Simplenote/SPAppDelegate.m [hunk 1]
```diff
@@ -947,11 +946,7 @@ - (void)setupAppRatings
     if ([NSProcessInfo isRunningTests]) {
         return;
     }
-    
-    // Initialize AppbotX
-    [[ABXApiClient instance] setApiKey:[SPCredentials appbotKey]];
-    
-    // Initialize AppRatings Helper
```
Comment (bummytime) [inline Simplenote/SPAppDelegate.m]: 🎉

**Comment by jleandroperez** [comment]
Thank you Bummy!!!
