### PR TITLE
Fixing Email Validation

### LINKED ISSUE #832: Conflicting detection/validation of email address
[`NSPredicate+Email`](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/NSPredicate%2BEmail.swift#L11) says an email as long as it has an `@` and ends in a TLD of at least two characters.

`".+@([A-Za-z0-9-]+\\.)+[A-Za-z]{2}[A-Za-z]*"`

[`NSString+Metadata`](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/Classes/NSString%2BMetadata.m#L21) adds tighter constraints and only allows TLDs with 2-4 characters, incorrectly rejecting many modern gTLDs such as `.coffee`, `.email`, and `.education`.

`"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"`

It would be ideal if these agreed or shared their validation. Currently `containsEmailAddress` is rejecting collaborators with valid email TLDs.

#3153839-zen

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're unifying the Email Validation routines, so that new TLDs are supported by the collaboration functionality.

Closes #832 
@aerych Sir!! you game for a quick PR?

Thanks in advance!!

### Test
1. Open any note
2. Press over the top right `( i )` icon
3. Press over `Collaborate`

- [ ] Verify you can add an email with a new (long) TLD, such as `test@test.coffee`

### Release
`RELEASE-NOTES.txt` was updated in 8ece212 with:
 
> Fixed a bug that prevented adding collaborators with email addresses that contain new TLDs

### CODE REVIEW

File: SimplenoteTests/NSStringSimplenoteTests.swift [hunk 1]
```diff
@@ -56,4 +56,22 @@ class NSStringSimplenoteTests: XCTestCase {
         XCTAssertEqual(hashA, hashC)
         XCTAssertEqual(hashB, hashC)
     }
+
+    /// Verifies that `isValidEmailAddress` returns  *true* when the receiver contains an email address with a non-standard TLD
+    ///
+    func testIsValidEmailAddressReturnsTrueWhenStringContainsNewTLDs() {
```
Comment (aerych) [inline SimplenoteTests/NSStringSimplenoteTests.swift:62]: I'm wondering if these tests would be better as part of `NSPredicateEmailTests` since that's the underlying logic being tested. The String extension is just for convenience.  
Just a thought.  No worries if you prefer it this way.

**Review by aerych — APPROVED** [review]
Hola @jleandroperez 👋 
Code looks good. Tests pass. I was able to add collaborators with long tlds to the list of collaborators.
I had one question/suggestion that is completely up to you sir.
:shipit:

**Comment by jleandroperez** [comment]
You're absolutely on spot. I've moved the unit tests over to the NSPredicate suite 😄 

Thank you sir!!
